swagger: '2.0'
info:
  title: Project Healthy
  version: 1.0.0
paths:
  /patient:
    get:
      summary: Retrieve a list of patients or a specific patient by ID
      parameters:
        - name: id
          in: query
          type: integer
          description: Patient ID (optional)
      responses:
        200:
          description: List of patients or a single patient
          schema:
            type: array
            items:
              $ref: '#/definitions/Patient'
    post:
      summary: Create a new patient
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Patient'
      responses:
        201:
          description: Patient created successfully
    put:
      summary: Update an existing patient
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Patient ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Patient'
      responses:
        200:
          description: Patient updated successfully
    delete:
      summary: Delete a patient by ID
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Patient ID
      responses:
        200:
          description: Patient deleted successfully

  /device:
    get:
      summary: Retrieve a list of devices or a specific device by ID
      parameters:
        - name: id
          in: query
          type: integer
          description: Device ID (optional)
      responses:
        200:
          description: List of devices or a single device
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
    post:
      summary: Create a new device
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Device'
      responses:
        201:
          description: Device created successfully
    put:
      summary: Update an existing device
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Device ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Device'
      responses:
        200:
          description: Device updated successfully
    delete:
      summary: Delete a device by ID
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Device ID
      responses:
        200:
          description: Device deleted successfully

  /entity:
    get:
      summary: Retrieve a list of device entities or a specific device entity by ID
      parameters:
        - name: id
          in: query
          type: integer
          description: Device Entity ID (optional)
      responses:
        200:
          description: List of device entities or a single entity
          schema:
            type: array
            items:
              $ref: '#/definitions/DeviceEntity'
    post:
      summary: Create a new device entity
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/DeviceEntity'
      responses:
        201:
          description: Device entity created successfully
    put:
      summary: Update an existing device entity
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Device Entity ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/DeviceEntity'
      responses:
        200:
          description: Device entity updated successfully
    delete:
      summary: Delete a device entity by ID
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          description: Device Entity ID
      responses:
        200:
          description: Device entity deleted successfully

  /telegrambot:
    get:
      summary: Retrieve a list of Telegram bots or a specific bot by ID
      parameters:
        - name: bot_id
          in: query
          type: integer
          description: Bot ID (optional)
      responses:
        200:
          description: List of Telegram bots or a single bot
          schema:
            type: array
            items:
              $ref: '#/definitions/TelegramBot'
    post:
      summary: Create a new Telegram bot
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TelegramBot'
      responses:
        201:
          description: Telegram bot created successfully
    put:
      summary: Update an existing Telegram bot
      parameters:
        - name: bot_id
          in: query
          type: integer
          required: true
          description: Bot ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TelegramBot'
      responses:
        200:
          description: Telegram bot updated successfully
    delete:
      summary: Delete a Telegram bot by ID
      parameters:
        - name: bot_id
          in: query
          type: integer
          required: true
          description: Bot ID
      responses:
        200:
          description: Telegram bot deleted successfully

  /endpoints:
    get:
      summary: Retrieve a list of endpoints or a specific endpoint by ID
      parameters:
        - name: endpoint_id
          in: query
          type: integer
          description: Endpoint ID (optional)
      responses:
        200:
          description: List of endpoints or a single endpoint
          schema:
            type: array
            items:
              $ref: '#/definitions/Endpoint'
    post:
      summary: Create a new endpoint
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Endpoint'
      responses:
        201:
          description: Endpoint created successfully
    put:
      summary: Update an existing endpoint
      parameters:
        - name: endpoint_id
          in: query
          type: integer
          required: true
          description: Endpoint ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Endpoint'
      responses:
        200:
          description: Endpoint updated successfully
    delete:
      summary: Delete an endpoint by ID
      parameters:
        - name: endpoint_id
          in: query
          type: integer
          required: true
          description: Endpoint ID
      responses:
        200:
          description: Endpoint deleted successfully

  /schedule:
    get:
      summary: Retrieve a list of schedules or a specific schedule by ID
      parameters:
        - name: schedule_id
          in: query
          type: integer
          description: Schedule ID (optional)
      responses:
        200:
          description: List of schedules or a single schedule
          schema:
            type: array
            items:
              $ref: '#/definitions/Schedule'
    post:
      summary: Create a new schedule
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Schedule'
      responses:
        201:
          description: Schedule created successfully
    put:
      summary: Update an existing schedule
      parameters:
        - name: schedule_id
          in: query
          type: integer
          required: true
          description: Schedule ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Schedule'
      responses:
        200:
          description: Schedule updated successfully
    delete:
      summary: Delete a schedule by ID
      parameters:
        - name: schedule_id
          in: query
          type: integer
          required: true
          description: Schedule ID
      responses:
        200:
          description: Schedule deleted successfully

  /entityconfig:
    get:
      summary: Retrieve a list of entity configurations or a specific configuration by ID
      parameters:
        - name: config_id
          in: query
          type: integer
          description: Configuration ID (optional)
      responses:
        200:
          description: List of entity configurations or a single configuration
          schema:
            type: array
            items:
              $ref: '#/definitions/EntityConfiguration'
    post:
      summary: Create a new entity configuration
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EntityConfiguration'
      responses:
        201:
          description: Entity configuration created successfully
    put:
      summary: Update an existing entity configuration
      parameters:
        - name: config_id
          in: query
          type: integer
          required: true
          description: Configuration ID
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/EntityConfiguration'
      responses:
        200:
          description: Entity configuration updated successfully
    delete:
      summary: Delete an entity configuration by ID
      parameters:
        - name: config_id
          in: query
          type: integer
          required: true
          description: Configuration ID
      responses:
        200:
          description: Entity configuration deleted successfully

  /configkeys:
    get:
      summary: Retrieve a list of configuration keys or a specific key by its name
      parameters:
        - name: config_key
          in: query
          type: string
          description: Configuration key (optional)
      responses:
        200:
          description: List of configuration keys or a single key
          schema:
            type: array
            items:
              $ref: '#/definitions/ConfigKey'
    post:
      summary: Create a new configuration key
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ConfigKey'
      responses:
        201:
          description: Configuration key created successfully
    put:
      summary: Update an existing configuration key
      parameters:
        - name: config_key
          in: query
          type: string
          required: true
          description: Configuration key
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ConfigKey'
      responses:
        200:
          description: Configuration key updated successfully
    delete:
      summary: Delete a configuration key by its name
      parameters:
        - name: config_key
          in: query
          type: string
          required: true
          description: Configuration key
      responses:
        200:
          description: Configuration key deleted successfully

  /login:
    post:
      summary: Authenticate a user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        200:
          description: Authentication successful
          schema:
            $ref: '#/definitions/LoginResponse'
        401:
          description: Authentication failed

definitions:
  Patient:
    type: object
    properties:
      name:
        type: string
      address:
        type: string
      emergency_contact:
        type: string
      passport_code:
        type: string
      admin_id:
        type: integer
  Device:
    type: object
    properties:
      mac_address:
        type: string
      device_name:
        type: string
      device_type:
        type: string
      location:
        type: string
      is_active:
        type: boolean
      patient_id:
        type: integer
      admin_id:
        type: integer
      thingspeak_channel_key:
        type: string
  DeviceEntity:
    type: object
    properties:
      entity_type:
        type: string
      entity_name:
        type: string
      device_id:
        type: integer
      is_active:
        type: boolean
      last_reading:
        type: string
      last_reading_timestamp:
        type: string
      service_id:
        type: integer
      thingspeak_field_id:
        type: integer
  TelegramBot:
    type: object
    properties:
      bot_token:
        type: string
      chat_id:
        type: string
      patient_id:
        type: integer
  Endpoint:
    type: object
    properties:
      service_id:
        type: integer
      entity_id:
        type: integer
      endpoint:
        type: string
  Schedule:
    type: object
    properties:
      entity_id:
        type: integer
      day_of_week:
        type: string
        enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
      start_time:
        type: string
      end_time:
        type: string
      action:
        type: string
        enum: [ON, OFF]
      repeat:
        type: boolean
  EntityConfiguration:
    type: object
    properties:
      entity_id:
        type: integer
      config_key:
        type: string
      config_value:
        type: string
  ConfigKey:
    type: object
    properties:
      config_key:
        type: string
      description:
        type: string
      value_type:
        type: string
        enum: [numeric, boolean, string, json]
      apply_to:
        type: string
        enum: [sensor, actuator]
  Login:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  LoginResponse:
    type: object
    properties:
      status:
        type: string
      user:
        type: object
